#!/usr/bin/env python3
"""Turn a WAV file into src/alert_sample.h (16 kHz signed 16-bit mono PCM).

Usage:
    python tools/gen_alert_sound.py warning.wav > src/alert_sample.h
    pio run -e esp32-s3-amoled-175 -t upload

Then pick "Custom sample" under Alert sound on the config page.

WAV only, deliberately: Python's stdlib reads WAV natively, so this needs no ffmpeg
and no pip installs. If you have an MP3, convert it first with Audacity, VLC
(Media > Convert/Save) or any online converter — 16 kHz mono is ideal but anything
will do, since this script resamples and downmixes.

The ES8311 runs at 16 kHz, so that is the target rate. Keep clips short: the alert
fires on live traffic events, and every second costs 32 KB of flash.
"""

import sys
import wave

TARGET_RATE = 16000
MAX_SECONDS = 4.0


def read_wav(path):
    with wave.open(path, "rb") as w:
        if w.getsampwidth() != 2:
            sys.exit(f"error: need 16-bit WAV, got {w.getsampwidth() * 8}-bit. "
                     "Re-export as 16-bit PCM.")
        rate = w.getframerate()
        channels = w.getnchannels()
        frames = w.readframes(w.getnframes())

    # bytes -> list of per-channel-interleaved ints
    samples = []
    for i in range(0, len(frames) - 1, 2):
        v = frames[i] | (frames[i + 1] << 8)
        if v >= 0x8000:
            v -= 0x10000
        samples.append(v)

    # downmix to mono by averaging channels
    if channels > 1:
        mono = []
        for i in range(0, len(samples) - channels + 1, channels):
            mono.append(sum(samples[i:i + channels]) // channels)
        samples = mono

    return samples, rate


def resample(samples, src_rate, dst_rate):
    """Linear interpolation. Fine for a short alert cue."""
    if src_rate == dst_rate:
        return samples
    out_n = int(len(samples) * dst_rate / src_rate)
    out = []
    for i in range(out_n):
        pos = i * src_rate / dst_rate
        i0 = int(pos)
        i1 = min(i0 + 1, len(samples) - 1)
        frac = pos - i0
        out.append(int(samples[i0] * (1.0 - frac) + samples[i1] * frac))
    return out


def normalize(samples, peak=0.89):
    """Scale up to `peak` of full scale so quiet source files aren't inaudible,
    leaving a little headroom so the speaker amp doesn't clip on transients."""
    hi = max((abs(s) for s in samples), default=0)
    if hi == 0:
        return samples
    gain = (32767 * peak) / hi
    return [max(-32768, min(32767, int(s * gain))) for s in samples]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = sys.argv[1]

    samples, rate = read_wav(path)
    samples = resample(samples, rate, TARGET_RATE)

    limit = int(TARGET_RATE * MAX_SECONDS)
    truncated = len(samples) > limit
    if truncated:
        samples = samples[:limit]
        # fade the last 10 ms so a hard cut doesn't click
        fade = int(TARGET_RATE * 0.01)
        for i in range(fade):
            samples[-1 - i] = int(samples[-1 - i] * i / fade)

    samples = normalize(samples)

    secs = len(samples) / TARGET_RATE
    kb = len(samples) * 2 / 1024
    # ASCII only: stdout redirects on Windows default to cp1252 and mangle em-dashes.
    print("#pragma once")
    print("// GENERATED by tools/gen_alert_sound.py - do not edit by hand.")
    print(f"// source: {path}")
    print(f"// {secs:.2f} s @ {TARGET_RATE} Hz mono, {kb:.1f} KB of flash"
          + (" (TRUNCATED)" if truncated else ""))
    print("//")
    print("// Check the source sound's licence permits redistribution before committing")
    print("// this file to a public repo - it embeds the audio as data.")
    print("#include <stdint.h>")
    print()
    print(f"#define ALERT_SAMPLE_RATE {TARGET_RATE}")
    print(f"#define ALERT_SAMPLE_LEN {len(samples)}")
    print("static const int16_t ALERT_SAMPLE[ALERT_SAMPLE_LEN] = {")
    for i in range(0, len(samples), 12):
        row = ", ".join(f"{v:6d}" for v in samples[i:i + 12])
        print(f"    {row},")
    print("};")

    sys.stderr.write(
        f"ok: {secs:.2f}s, {len(samples)} samples, {kb:.1f} KB flash"
        + (" (truncated to 4 s)\n" if truncated else "\n"))


if __name__ == "__main__":
    main()
