#!/usr/bin/env python3
"""Convert a splash artwork image into an embedded JPEG for the firmware.

Needs Pillow (like make_gif.py, and unlike grab_screens.py which stays stdlib-only):

    pip install pillow
    python tools/make_splash.py <image> [--size 720] [--out src/boards/splash_720.h]

Why a baked image at all: the splash used to be painted per-pixel from polygons at
runtime. That is fine for a scope and a gradient, but it cannot produce a photorealistic
aircraft, and three attempts at a vector silhouette all read badly on the real panel. The
boards have 16-32 MB of flash and already link TJpg_Decoder, so carrying a ~150 KB JPEG
costs nothing meaningful.

Two things are removed on the way in:
  * The title plate area is painted out. The source has the version baked into it, which
    would freeze at whatever it said the day the image was made; LVGL draws the plate and
    the live FW_VERSION on top instead.
  * A vignette is applied so the artwork fades to black before the round bezel, which
    also disposes of anything sitting in the square corners.
"""
import argparse
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit("needs Pillow:  pip install pillow")


def build(src_path, size, out_path, var, keep_plate=False):
    im = Image.open(src_path).convert("RGB")
    w, h = im.size
    side = min(w, h)
    im = im.crop(((w - side) // 2, (h - side) // 2, (w + side) // 2, (h + side) // 2))

    # Paint out the baked title plate unless the artwork is meant to keep it. Only needed
    # when the source has a version number baked in, which would freeze at whatever it
    # said the day the image was made.
    if not keep_plate:
        x0, y0, x1, y1 = int(side * 0.13), int(side * 0.63), int(side * 0.87), int(side * 0.95)
        patch = im.crop((x0, y0, x1, y1)).filter(ImageFilter.GaussianBlur(24))
        patch = Image.eval(patch, lambda v: int(v * 0.45))
        im.paste(patch, (x0, y0))

    im = im.resize((size, size), Image.LANCZOS)

    # Vignette: fade to black outside the panel circle.
    px = im.load()
    c = (size - 1) / 2.0
    inner, outer = c * 0.86, c * 1.0
    for y in range(size):
        for x in range(size):
            dx, dy = x - c, y - c
            dist = (dx * dx + dy * dy) ** 0.5
            if dist <= inner:
                continue
            k = 0.0 if dist >= outer else 1.0 - (dist - inner) / (outer - inner)
            r, g, b = px[x, y]
            px[x, y] = (int(r * k), int(g * k), int(b * k))

    tmp = out_path + ".jpg"
    im.save(tmp, "JPEG", quality=86, optimize=True, progressive=False)  # TJpgDec: baseline only
    data = open(tmp, "rb").read()
    os.remove(tmp)

    with open(out_path, "w", newline="") as f:
        f.write("#pragma once\n")
        f.write("// Splash artwork, %dx%d baseline JPEG. Generated by tools/make_splash.py --\n" % (size, size))
        f.write("// do not hand-edit. Decoded into the splash canvas by TJpgDec at boot.\n")
        f.write("// The title plate and version are drawn live by LVGL on top, not baked in.\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const uint8_t %s[] = {\n" % var)
        for i in range(0, len(data), 16):
            f.write("    " + ",".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
    print("%s  %dx%d  %.0f KB" % (out_path, size, size, len(data) / 1024.0))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image")
    ap.add_argument("--size", type=int, default=720)
    ap.add_argument("--out", default=None)
    ap.add_argument("--var", default=None)
    ap.add_argument("--keep-plate", action="store_true",
                    help="source already has a title plate with no version baked in")
    a = ap.parse_args()
    size = a.size
    out = a.out or ("src/boards/splash_%d.h" % size)
    var = a.var or ("kSplashJpg%d" % size)
    build(a.image, size, out, var, a.keep_plate)


if __name__ == "__main__":
    main()
