#pragma once
// Airline lookup table: ICAO callsign prefix -> IATA code + display name.
//
// ADS-B callsigns carry the 3-letter ICAO operator code ("RYR4TG" = Ryanair), while
// logo CDNs are keyed by the 2-letter IATA code ("FR"). This table bridges the two and
// supplies a human-readable name, so the detail card can label the operator even when
// no logo is available (or WiFi is down). Covers the operators most likely to appear on
// a hobby receiver; unknown prefixes simply fall back to showing the raw callsign.
#include <stdint.h>

struct AirlineRec {
    char        icao[4];   // ICAO operator code (callsign prefix)
    char        iata[3];   // IATA code (logo CDN key); empty if the carrier has none
    const char *name;      // display name
};

static const AirlineRec AIRLINES[] = {
    // --- North America ---
    {"AAL", "AA", "American Airlines"},
    {"AAY", "G4", "Allegiant Air"},
    {"ACA", "AC", "Air Canada"},
    {"ASA", "AS", "Alaska Airlines"},
    {"ASH", "YV", "Mesa Airlines"},
    {"DAL", "DL", "Delta Air Lines"},
    {"EDV", "9E", "Endeavor Air"},
    {"ENY", "MQ", "Envoy Air"},
    {"FFT", "F9", "Frontier Airlines"},
    {"FLE", "F8", "Flair Airlines"},
    {"HAL", "HA", "Hawaiian Airlines"},
    {"JBU", "B6", "JetBlue Airways"},
    {"JIA", "OH", "PSA Airlines"},
    {"JZA", "QK", "Jazz Aviation"},
    {"NKS", "NK", "Spirit Airlines"},
    {"POE", "PD", "Porter Airlines"},
    {"QXE", "QX", "Horizon Air"},
    {"ROU", "RV", "Air Canada Rouge"},
    {"RPA", "YX", "Republic Airways"},
    {"SCX", "SY", "Sun Country"},
    {"SKW", "OO", "SkyWest Airlines"},
    {"SWA", "WN", "Southwest Airlines"},
    {"TSC", "TS", "Air Transat"},
    {"UAL", "UA", "United Airlines"},
    {"WEN", "WR", "WestJet Encore"},
    {"WJA", "WS", "WestJet"},

    // --- Europe ---
    {"AEA", "UX", "Air Europa"},
    {"AEE", "A3", "Aegean Airlines"},
    {"AFR", "AF", "Air France"},
    {"ANE", "YW", "Air Nostrum"},
    {"AUA", "OS", "Austrian Airlines"},
    {"AZA", "AZ", "Alitalia"},
    {"BAW", "BA", "British Airways"},
    {"BTI", "BT", "airBaltic"},
    {"CFG", "DE", "Condor"},
    {"CSA", "OK", "Czech Airlines"},
    {"CTN", "OU", "Croatia Airlines"},
    {"DLH", "LH", "Lufthansa"},
    {"EIN", "EI", "Aer Lingus"},
    {"EWG", "EW", "Eurowings"},
    {"EZY", "U2", "easyJet"},
    {"FIN", "AY", "Finnair"},
    {"IBE", "IB", "Iberia"},
    {"IBS", "I2", "Iberia Express"},
    {"ICE", "FI", "Icelandair"},
    {"ITY", "AZ", "ITA Airways"},
    {"JAF", "TB", "TUI fly Belgium"},
    {"LGL", "LG", "Luxair"},
    {"LOT", "LO", "LOT Polish Airlines"},
    {"LZB", "FB", "Bulgaria Air"},
    {"NAX", "DY", "Norwegian"},
    {"PGT", "PC", "Pegasus Airlines"},
    {"RYR", "FR", "Ryanair"},
    {"SAS", "SK", "SAS"},
    {"SWR", "LX", "SWISS"},
    {"SXS", "XQ", "SunExpress"},
    {"TAP", "TP", "TAP Air Portugal"},
    {"TFL", "OR", "TUI fly Netherlands"},
    {"THY", "TK", "Turkish Airlines"},
    {"TOM", "BY", "TUI Airways"},
    {"TRA", "HV", "Transavia"},
    {"TUI", "X3", "TUI fly"},
    {"TVF", "TO", "Transavia France"},
    {"VIR", "VS", "Virgin Atlantic"},
    {"VLG", "VY", "Vueling"},
    {"VOE", "V7", "Volotea"},
    {"WZZ", "W6", "Wizz Air"},

    // --- Middle East / Central Asia ---
    {"ABY", "G9", "Air Arabia"},
    {"AHY", "J2", "Azerbaijan Airlines"},
    {"ELY", "LY", "El Al"},
    {"ETD", "EY", "Etihad Airways"},
    {"FDB", "FZ", "flydubai"},
    {"GFA", "GF", "Gulf Air"},
    {"IAW", "IA", "Iraqi Airways"},
    {"IRA", "IR", "Iran Air"},
    {"KAC", "KU", "Kuwait Airways"},
    {"KZR", "KC", "Air Astana"},
    {"MEA", "ME", "Middle East Airlines"},
    {"OMA", "WY", "Oman Air"},
    {"QTR", "QR", "Qatar Airways"},
    {"RJA", "RJ", "Royal Jordanian"},
    {"SVA", "SV", "Saudia"},
    {"UAE", "EK", "Emirates"},
    {"UZB", "HY", "Uzbekistan Airways"},

    // --- Asia / Pacific ---
    {"AAR", "OZ", "Asiana Airlines"},
    {"AIC", "AI", "Air India"},
    {"AIQ", "FD", "Thai AirAsia"},
    {"ALK", "UL", "SriLankan Airlines"},
    {"ANA", "NH", "All Nippon Airways"},
    {"ANZ", "NZ", "Air New Zealand"},
    {"AXB", "IX", "Air India Express"},
    {"AXM", "AK", "AirAsia"},
    {"BBC", "BG", "Biman Bangladesh"},
    {"BKP", "PG", "Bangkok Airways"},
    {"CAL", "CI", "China Airlines"},
    {"CCA", "CA", "Air China"},
    {"CEB", "5J", "Cebu Pacific"},
    {"CES", "MU", "China Eastern"},
    {"CHH", "HU", "Hainan Airlines"},
    {"CPA", "CX", "Cathay Pacific"},
    {"CQH", "9C", "Spring Airlines"},
    {"CSN", "CZ", "China Southern"},
    {"CSZ", "ZH", "Shenzhen Airlines"},
    {"CXA", "MF", "XiamenAir"},
    {"EVA", "BR", "EVA Air"},
    {"GIA", "GA", "Garuda Indonesia"},
    {"HVN", "VN", "Vietnam Airlines"},
    {"IGO", "6E", "IndiGo"},
    {"JAL", "JL", "Japan Airlines"},
    {"JST", "JQ", "Jetstar"},
    {"KAL", "KE", "Korean Air"},
    {"LNI", "JT", "Lion Air"},
    {"MAS", "MH", "Malaysia Airlines"},
    {"MGL", "OM", "MIAT Mongolian"},
    {"NOK", "DD", "Nok Air"},
    {"PAL", "PR", "Philippine Airlines"},
    {"PIA", "PK", "Pakistan Intl"},
    {"QFA", "QF", "Qantas"},
    {"RBA", "BI", "Royal Brunei"},
    {"REX", "ZL", "Rex"},
    {"SCO", "TR", "Scoot"},
    {"SEJ", "SG", "SpiceJet"},
    {"SIA", "SQ", "Singapore Airlines"},
    {"THA", "TG", "Thai Airways"},
    {"VJC", "VJ", "VietJet Air"},
    {"VOZ", "VA", "Virgin Australia"},

    // --- Africa ---
    {"DAH", "AH", "Air Algerie"},
    {"ETH", "ET", "Ethiopian Airlines"},
    {"KQA", "KQ", "Kenya Airways"},
    {"MAU", "MK", "Air Mauritius"},
    {"MSR", "MS", "EgyptAir"},
    {"RAM", "AT", "Royal Air Maroc"},
    {"RWD", "WB", "RwandAir"},
    {"SAA", "SA", "South African Airways"},
    {"TAR", "TU", "Tunisair"},

    // --- Latin America ---
    {"AMX", "AM", "Aeromexico"},
    {"ARG", "AR", "Aerolineas Argentinas"},
    {"AVA", "AV", "Avianca"},
    {"AZU", "AD", "Azul"},
    {"CMP", "CM", "Copa Airlines"},
    {"GLO", "G3", "Gol"},
    {"LAN", "LA", "LATAM Airlines"},
    {"SKU", "H2", "Sky Airline"},
    {"TAM", "JJ", "LATAM Brasil"},
    {"VIV", "VB", "Viva Aerobus"},
    {"VOI", "Y4", "Volaris"},

    // --- Russia / CIS ---
    {"AFL", "SU", "Aeroflot"},
    {"PBD", "DP", "Pobeda"},
    {"SBI", "S7", "S7 Airlines"},
    {"SVR", "U6", "Ural Airlines"},
    {"UTA", "UT", "UTair"},

    // --- Cargo ---
    {"ABW", "RU", "AirBridgeCargo"},
    {"BCS", "QY", "DHL Air"},
    {"CLX", "CV", "Cargolux"},
    {"FDX", "FX", "FedEx Express"},
    {"GEC", "LH", "Lufthansa Cargo"},
    {"GTI", "5Y", "Atlas Air"},
    {"NCA", "KZ", "Nippon Cargo"},
    {"TAY", "3V", "ASL Airlines"},
    {"UPS", "5X", "UPS Airlines"},
};

static const int AIRLINES_NUM = (int)(sizeof(AIRLINES) / sizeof(AIRLINES[0]));
